'use client';

import { usePOSStore } from '@/lib/store';
import { SyncService } from '@/services/sync';
import { useUser } from "@clerk/nextjs";
import { X, Lock, TrendingUp, CreditCard, Banknote, Printer } from 'lucide-react';
import { usePrinter } from '@/hooks/usePrinter';
import { motion, AnimatePresence } from 'framer-motion';
import { useState } from 'react';

interface DailyCloseModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export function DailyCloseModal({ isOpen, onClose }: DailyCloseModalProps) {
    const { getDailyTotal } = usePOSStore();
    const totals = getDailyTotal();
    const [isSyncing, setIsSyncing] = useState(false);

    const { user } = useUser();

    const handleCloseRegister = async () => {
        setIsSyncing(true);

        const tenantId = (user?.publicMetadata?.tenantId as string);
        const outletId = (user?.publicMetadata?.outletId as string);

        if (!tenantId || !outletId) {
            alert("Error: Missing Tenant/Outlet ID. Please login again.");
            setIsSyncing(false);
            return;
        }

        const saasContext = { tenantId, outletId };

        const dailyPayload = {
            date: new Date().toISOString(),
            cashSales: totals.cash,
            cardSales: totals.card,
            upiSales: 0, // Add UPI tracking if needed
            totalSales: totals.total,
            ordersCount: 0 // We should track this in store if needed, or backend can count
        };

        try {
            await SyncService.pushMutation('CLOSE_DAY', dailyPayload, saasContext);
            alert('Register Closed & Sales Synced!');
            onClose();
        } catch (error) {
            alert('Failed to sync. Queued for offline.');
            onClose();
        } finally {
            setIsSyncing(false);
        }
    };

    if (!isOpen) return null;

    const { printReceipt } = usePrinter();

    const handlePrintReport = () => {
        const content = document.createElement('div');
        content.id = 'daily-report-print';
        content.className = 'p-4 bg-white font-mono text-sm';
        content.innerHTML = `
            <div class="text-center font-bold text-lg mb-4">DAILY CLOSING REPORT</div>
            <div class="mb-2">Date: ${new Date().toLocaleDateString()}</div>
            <div class="mb-2">Time: ${new Date().toLocaleTimeString()}</div>
            <div class="mb-4">Staff: ${user?.firstName || 'Unknown'}</div>
            <div class="border-b border-dashed border-black mb-4"></div>
            
            <div class="flex justify-between mb-2">
                <span>Cash Sales:</span>
                <span class="font-bold">₹${totals.cash.toFixed(2)}</span>
            </div>
            <div class="flex justify-between mb-2">
                <span>Card/QR Sales:</span>
                <span class="font-bold">₹${totals.card.toFixed(2)}</span>
            </div>
            
            <div class="border-b border-dashed border-black my-4"></div>
            
            <div class="flex justify-between text-lg font-bold">
                <span>TOTAL REVENUE:</span>
                <span>₹${totals.total.toFixed(2)}</span>
            </div>
            
            <div class="border-b border-dashed border-black mt-4 mb-4"></div>
            <div class="text-center text-xs">Generated by Beloop POS</div>
        `;

        document.body.appendChild(content);
        printReceipt('daily-report-print');
        document.body.removeChild(content);
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden"
                >
                    <div className="bg-gray-900 text-white p-6 flex justify-between items-center">
                        <h2 className="text-2xl font-bold flex items-center gap-2">
                            <Lock size={24} />
                            Close Register
                        </h2>
                        <button onClick={onClose} className="p-2 hover:bg-gray-800 rounded-full transition-colors" aria-label="Close modal">
                            <X size={24} />
                        </button>
                    </div>

                    <div className="p-6 space-y-6">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="p-4 bg-green-50 rounded-xl border border-green-100">
                                <div className="flex items-center gap-2 text-green-700 mb-1">
                                    <Banknote size={18} />
                                    <span className="font-bold text-sm">Cash Sales</span>
                                </div>
                                <p className="text-2xl font-bold text-gray-900">₹{totals.cash.toFixed(2)}</p>
                            </div>
                            <div className="p-4 bg-blue-50 rounded-xl border border-blue-100">
                                <div className="flex items-center gap-2 text-blue-700 mb-1">
                                    <CreditCard size={18} />
                                    <span className="font-bold text-sm">Card/QR</span>
                                </div>
                                <p className="text-2xl font-bold text-gray-900">₹{totals.card.toFixed(2)}</p>
                            </div>
                        </div>

                        <div className="p-6 bg-gray-50 rounded-xl border border-gray-200 text-center">
                            <p className="text-gray-500 font-medium mb-1">Total Revenue Today</p>
                            <p className="text-4xl font-extrabold text-gray-900">₹{totals.total.toFixed(2)}</p>
                        </div>

                        <div className="flex gap-3">
                            <button
                                onClick={handlePrintReport}
                                className="flex-1 bg-gray-100 text-gray-700 py-4 rounded-xl font-bold text-lg hover:bg-gray-200 transition-all flex items-center justify-center gap-2"
                            >
                                <Printer size={20} />
                                Print Report
                            </button>
                            <button
                                onClick={handleCloseRegister}
                                disabled={isSyncing}
                                className="flex-[2] bg-rose-600 text-white py-4 rounded-xl font-bold text-lg hover:bg-rose-700 transition-all shadow-lg shadow-rose-500/20 disabled:opacity-70"
                            >
                                {isSyncing ? 'Syncing...' : 'Close & Sync'}
                            </button>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
}
